name: Kernel Config - A13 5.15

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs:
      kernelsu_variant:
        required: false
        type: string

jobs:
  build-kernels-a13-5-15:
    strategy:
      fail-fast: true
      matrix:
        include:
          - sub_level: "123"
            os_patch_level: "2023-11"
          - sub_level: "137"
            os_patch_level: "2024-01"
          - sub_level: "144"
            os_patch_level: "2024-03"
          - sub_level: "148"
            os_patch_level: "2024-05"
          - sub_level: "149"
            os_patch_level: "2024-07"
          - sub_level: "151"
            os_patch_level: "2024-08"
          - sub_level: "153"
            os_patch_level: "2024-09"
          - sub_level: "167"
            os_patch_level: "2024-11"
          - sub_level: "170"
            os_patch_level: "2025-01"
          - sub_level: "178"
            os_patch_level: "2025-03"
          - sub_level: "180"
            os_patch_level: "2025-05"
          - sub_level: "185"
            os_patch_level: "2025-07"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android13"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}