name: Kernel Config - A13 5.10

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs:
      kernelsu_variant:
        required: false
        type: string

jobs:
  build-kernels-a13-5-10:
    strategy:
      fail-fast: true
      matrix:
        include:
          - sub_level: "198"
            os_patch_level: "2024-01"
          - sub_level: "205"
            os_patch_level: "2024-03"
          - sub_level: "209"
            os_patch_level: "2024-05"
          - sub_level: "210"
            os_patch_level: "2024-06"
          - sub_level: "214"
            os_patch_level: "2024-07"
          - sub_level: "218"
            os_patch_level: "2024-08"
          - sub_level: "223"
            os_patch_level: "2024-11"
          - sub_level: "228"
            os_patch_level: "2025-01"
          - sub_level: "234"
            os_patch_level: "2025-03"
          - sub_level: "236"
            os_patch_level: "2025-05"
          - sub_level: "238"
            os_patch_level: "2025-07"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android13"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}